import Card from "./Card.jsx";
import Button from "./Button.jsx";
import PayrollPreview from "./PayrollPreview.jsx";
import { CHF } from "../utils/calc.js";

function Field({ label, hint, children }) {
  return <label className="block"><div className="flex justify-between gap-3 mb-1"><span className="text-sm font-semibold text-putzit-dark">{label}</span>{hint ? <span className="text-xs text-putzit-grey">{hint}</span> : null}</div>{children}</label>;
}
function Input(props) { return <input {...props} className="w-full rounded-2xl px-4 py-3 border bg-white text-sm outline-none min-h-[44px]" style={{ borderColor: "#E6EEF2" }} />; }
function Select(props) { return <select {...props} className="w-full rounded-2xl px-4 py-3 border bg-white text-sm outline-none min-h-[44px]" style={{ borderColor: "#E6EEF2" }}>{props.children}</select>; }

export default function PayrollForm({ values, setValues, c, pdfRef, loadingPdf, onGeneratePdf, publicMode = false }) {
  function setValue(key, value) { setValues((prev) => ({ ...prev, [key]: value })); }
  return (
    <main className={publicMode ? "max-w-7xl mx-auto px-4 sm:px-5 py-8 sm:py-10 grid grid-cols-1 lg:grid-cols-[430px_1fr] gap-6" : "max-w-6xl mx-auto px-5 py-8 grid grid-cols-1 lg:grid-cols-[430px_1fr] gap-6"}>
      <div className="no-print space-y-5">
        <Card><div className="p-5 space-y-4"><h1 className="text-2xl font-black">Lohnabrechnung erstellen</h1><p className="text-sm text-putzit-grey">{publicMode ? "Gratis Formular ohne Registrierung." : "Abrechnung aus der Plattform erstellen."}</p><Field label="Lohnmonat"><Input type="month" value={values.month} onChange={(e) => setValue("month", e.target.value)} /></Field></div></Card>
        <Card><div className="p-5 space-y-4"><h2 className="font-bold">Arbeitgeber & Reinigungskraft</h2><Field label="Arbeitgeber"><Input value={values.employerName} onChange={(e) => setValue("employerName", e.target.value)} /></Field><Field label="Adresse Arbeitgeber"><Input value={values.employerAddress} onChange={(e) => setValue("employerAddress", e.target.value)} /></Field><Field label="Reinigungskraft"><Input value={values.employeeName} onChange={(e) => setValue("employeeName", e.target.value)} /></Field><Field label="Adresse Reinigungskraft"><Input value={values.employeeAddress} onChange={(e) => setValue("employeeAddress", e.target.value)} /></Field></div></Card>
        <Card><div className="p-5 space-y-4"><h2 className="font-bold">Arbeitsstunden & Lohn</h2><Field label="Gearbeitete Stunden" hint="z.B. 4.75 = 4h 45min"><Input type="number" step="0.25" value={values.hours} onChange={(e) => setValue("hours", e.target.value)} /></Field><Field label="Nettostundenlohn"><Input type="number" step="0.05" value={values.netHourly} onChange={(e) => setValue("netHourly", e.target.value)} /></Field><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><Field label="Kanton"><Select value={values.canton} onChange={(e) => setValue("canton", e.target.value)}><option>BE</option><option>ZH</option><option>AG</option><option>SO</option><option>LU</option><option>VD</option><option>GE</option></Select></Field><Field label="Quellensteuer %"><Input type="number" step="0.1" value={values.sourceTaxRate} onChange={(e) => setValue("sourceTaxRate", e.target.value)} /></Field></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><Field label="Ferien %"><Input type="number" step="0.01" value={values.vacationRate} onChange={(e) => setValue("vacationRate", e.target.value)} /></Field><Field label="Auslagen CHF"><Input type="number" step="0.05" value={values.expenses} onChange={(e) => setValue("expenses", e.target.value)} /></Field></div></div></Card>
        <Card><div className="p-5 space-y-4"><h2 className="font-bold">Abzüge</h2><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><Field label="AHV/IV/EO %"><Input type="number" step="0.001" value={values.ahvRate} onChange={(e) => setValue("ahvRate", e.target.value)} /></Field><Field label="ALV %"><Input type="number" step="0.01" value={values.alvRate} onChange={(e) => setValue("alvRate", e.target.value)} /></Field></div><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={values.nbuActive} onChange={(e) => setValue("nbuActive", e.target.checked)} /> NBU aktiv</label>{values.nbuActive ? <Field label="NBU %"><Input type="number" step="0.01" value={values.nbuRate} onChange={(e) => setValue("nbuRate", e.target.value)} /></Field> : null}<Field label="Auszahlungsdatum"><Input value={values.payoutDate} onChange={(e) => setValue("payoutDate", e.target.value)} /></Field></div></Card>
        <Card><div className="p-5 space-y-3"><div className="rounded-2xl p-4 text-sm bg-putzit-light"><div className="font-bold mb-1">Live Berechnung aktiv</div><div className="text-putzit-grey">Alle Werte werden automatisch neu berechnet.</div></div><div className="flex justify-between"><span>Netto Auszahlung Lohn</span><b>{CHF.format(c.netPayout)}</b></div><div className="flex justify-between"><span>Auslagen</span><b>{CHF.format(c.expenses)}</b></div><div className="flex justify-between text-lg"><span>Total Auszahlung</span><b>{CHF.format(c.totalPayout)}</b></div><div className="grid grid-cols-1 gap-3 pt-3"><Button onClick={onGeneratePdf} className="w-full">{loadingPdf ? "PDF wird erstellt..." : "PDF erstellen & herunterladen"}</Button><Button secondary className="w-full" onClick={() => alert(publicMode ? "In der Profiversion können Abrechnungen gespeichert werden." : "Abrechnung wurde im Archiv gespeichert.")}>{publicMode ? "Speichern mit Login" : "Im Archiv speichern"}</Button></div></div></Card>
      </div>
      <div id="pdf-preview" ref={pdfRef}><PayrollPreview values={values} /></div>
    </main>
  );
}
